In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/shahddaymann/libraries-docs/pandas_complete_guide.pdf
/kaggle/input/datasets/shahddaymann/libraries-docs/scikit-learn-docs.pdf
/kaggle/input/datasets/shahddaymann/libraries-docs/NumPy_Complete_Guide.pdf
/kaggle/input/datasets/shahddaymann/libraries-docs/numpy-ref.pdf

In [2]:
!pip install langchain_community

Collecting langchain_community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (3.13.5)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.4.3)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain_community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Collecting langchain-core<2.0.0,>=1.4.0 (from langchain_community)
  Downloading langchain_core-1.6.1-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.7.34)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.14.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (6.0.3)
Collecting requests<3.0.0,>=2.32.5 (from langchain_community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.49)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (9.1.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.23.0)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain_community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain_community) (2.12.3)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (1.33)
Collecting langchain-protocol>=0.0.17 (from langchain-core<2.0.0,>=1.4.0->langchain_community)
  Downloading langchain_protocol-0.0.19-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (26.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (0.14.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.2.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2026.4.22)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain_community) (3.4.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.0->langchain_community) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.0->langchain_community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.4.0->langchain_community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain_community) (3.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain_community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain_community) (2.41.4)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 9.6 MB/s eta 0:00:00:00:010:01
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 49.3 MB/s eta 0:00:00
Downloading langchain_core-1.6.1-py3-none-any.whl (571 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.5/571.5 kB 8.8 MB/s eta 0:00:00:00:01
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.1 MB/s eta 0:00:00
Downloading langchain_protocol-0.0.19-py3-none-any.whl (7.3 kB)
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Installing collected packages: requests, langchain-protocol, langchain-core, langchain-text-splitters, langchain-classic, langchain_community
  Attempting uninstall: requests
    Found existing installation: requests 2.32.4
    Uninstalling requests-2.32.4:
      Successfully uninstalled requests-2.32.4
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 1.3.1
    Uninstalling langchain-core-1.3.1:
      Successfully uninstalled langchain-core-1.3.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
moviepy 1.0.3 requires decorator<5.0,>=4.0.2, but you have decorator 5.3.1 which is incompatible.
Successfully installed langchain-classic-1.0.8 langchain-core-1.6.1 langchain-protocol-0.0.19 langchain-text-splitters-1.1.2 langchain_community-0.4.2 requests-2.34.2

In [3]:
from pathlib import Path
from langchain_community.document_loaders import PyPDFLoader
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
import re
import json
from collections import Counter

/tmp/ipykernel_58/1788431493.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import PyPDFLoader

# **Document Preparation**

# **Chunking**

In [4]:
PDF_FOLDER = Path(
    "/kaggle/input/datasets/shahddaymann/libraries-docs"
)

OUTPUT_FOLDER = Path(
    "/kaggle/working/final_chunks"
)

OUTPUT_FOLDER.mkdir(
    parents=True,
    exist_ok=True
)

In [5]:
GUIDE_PDFS = {
    "NumPy_Complete_Guide.pdf",
    "pandas_complete_guide.pdf",
}



CHUNK_SIZE = 2500
CHUNK_OVERLAP = 300

# Remove chunks that contain almost no useful information
MIN_CHUNK_SIZE = 100


splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP,
    separators=[
        "\n\n",
        "\n",
        ". ",
        " ",
        ""
    ]
)

In [6]:
def clean_text(text):
    """
    Clean common PDF extraction artifacts while preserving
    useful structure such as paragraphs and code.
    """

    if not text:
        return ""


    text = text.replace("\x7f", " ")
    text = text.replace("\u0000", " ")


    text = text.replace("●", "-")
    text = text.replace("•", "-")
    text = text.replace("▪", "-")
    text = text.replace("◦", "-")


    text = re.sub(
        r"(?m)^\s*l\s+",
        "- ",
        text
    )
    text = text.replace("\r\n", "\n")
    text = text.replace("\r", "\n")

    text = re.sub(
        r"[ \t]+",
        " ",
        text
    )


    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text
    )

    return text.strip()

In [7]:
NUMBERED_HEADING = re.compile(
    r"^\s*(\d+(?:\.\d+)*)\.\s+(.+?)\s*$"
)
def detect_numbered_heading(line):
    """
    Detect headings such as:

        1. Introduction
        2. Installation
        2.1 Series
        2.2 DataFrame
        11.1 Merge
    """

    match = NUMBERED_HEADING.match(line)

    if not match:
        return None

    number = match.group(1)
    title = match.group(2).strip()

    return number, title

In [8]:
def is_noise(line):
    """
    Remove obvious PDF extraction artifacts.
    """

    line = line.strip()

    if not line:
        return True


    if re.fullmatch(
        r"Page\s+\d+",
        line,
        flags=re.IGNORECASE
    ):
        return True

    if re.fullmatch(
        r"\d+",
        line
    ):
        return True

    return False

In [9]:
def remove_duplicate_lines(text):
    """
    PDFs sometimes repeat headers/footers.

    Remove only consecutive duplicate lines so that
    legitimate repeated content is not destroyed.
    """

    lines = text.splitlines()

    cleaned_lines = []

    previous = None

    for line in lines:

        normalized = line.strip()

        if (
            normalized
            and normalized == previous
        ):
            continue

        cleaned_lines.append(line)

        previous = normalized

    return "\n".join(cleaned_lines)

In [10]:
#LOAD ALL PDFs

all_pages = []

pdf_files = sorted(
    PDF_FOLDER.glob("*.pdf")
)

if not pdf_files:
    raise FileNotFoundError(
        f"No PDF files found in: {PDF_FOLDER}"
    )


print("=" * 80)
print("LOADING PDF FILES")
print("=" * 80)


for pdf_path in pdf_files:

    print(
        f"Loading: {pdf_path.name}"
    )

    try:

        loader = PyPDFLoader(
            str(pdf_path)
        )

        pages = loader.load()

    except Exception as e:

        print(
            f"ERROR loading {pdf_path.name}: {e}"
        )

        continue

    library_name = pdf_path.stem

    source_type = (
        "guide"
        if pdf_path.name in GUIDE_PDFS
        else "reference"
    )

    for page in pages:

        page.metadata["library"] = (
            library_name
        )

        page.metadata["source"] = (
            pdf_path.name
        )

        page.metadata["source_type"] = (
            source_type
        )


        raw_page = page.metadata.get(
            "page",
            0
        )

        try:
            page_number = int(raw_page) + 1
        except:
            page_number = 1

        page.metadata["page"] = (
            page_number
        )

    all_pages.extend(pages)


print()
print("=" * 80)
print(
    f"TOTAL PDF PAGES LOADED: "
    f"{len(all_pages)}"
)
print("=" * 80)




pages_by_source = {}

for page in all_pages:

    source = page.metadata["source"]

    if source not in pages_by_source:
        pages_by_source[source] = []

    pages_by_source[source].append(page)



def process_guide(
    pages,
    library,
    source
):
    """
    Process small curated guide PDFs.

    A heading is kept together with its explanation/code.

    Example:

        4. Creating Arrays

        np.array(...)
        np.zeros(...)
        np.ones(...)

    becomes one semantic section rather than a heading-only
    chunk.
    """

    # --------------------------------------------------------
    # Combine pages
    # --------------------------------------------------------

    full_text = "\n\n".join(
        page.page_content
        for page in pages
    )

    full_text = clean_text(
        full_text
    )

    full_text = remove_duplicate_lines(
        full_text
    )

    lines = full_text.splitlines()

    sections = []

    current_section = None
    current_subsection = None
    current_content = []

    def save_current_section():

        nonlocal current_content

        if not current_content:
            return

        content = "\n".join(
            current_content
        ).strip()

        if not content:
            return

        sections.append(
            {
                "content": content,
                "section": current_section,
                "subsection": current_subsection,
            }
        )

        current_content = []

    # --------------------------------------------------------
    # Parse lines
    # --------------------------------------------------------

    for line in lines:

        line = line.strip()

        if is_noise(line):
            continue

        heading = detect_numbered_heading(
            line
        )

        # ====================================================
        # Numbered heading
        # ====================================================

        if heading:

            number, title = heading

            # ------------------------------------------------
            # Save previous content
            # ------------------------------------------------

            if current_content:
                save_current_section()

            # ------------------------------------------------
            # Main section
            #
            # 1. Introduction
            # 2. Installation
            # ------------------------------------------------

            if "." not in number:

                current_section = (
                    f"{number}. {title}"
                )

                current_subsection = None

            # ------------------------------------------------
            # Subsection
            #
            # 2.1 Series
            # 2.2 DataFrame
            # ------------------------------------------------

            else:

                current_subsection = (
                    f"{number}. {title}"
                )

            # ------------------------------------------------
            # IMPORTANT:
            # Heading is part of the content.
            # ------------------------------------------------

            current_content = [
                line
            ]

        else:

            current_content.append(
                line
            )

    # --------------------------------------------------------
    # Save final section
    # --------------------------------------------------------

    if current_content:
        save_current_section()

    # --------------------------------------------------------
    # Convert sections to Documents
    # --------------------------------------------------------

    final_documents = []

    chunk_counter = 0

    for section in sections:

        content = section[
            "content"
        ].strip()

        # ----------------------------------------------------
        # Ignore tiny sections
        # ----------------------------------------------------

        if len(content) < MIN_CHUNK_SIZE:
            continue

        # ----------------------------------------------------
        # Small enough → keep intact
        # ----------------------------------------------------

        if len(content) <= CHUNK_SIZE:

            final_documents.append(
                Document(
                    page_content=content,

                    metadata={
                        "library": library,
                        "source": source,
                        "source_type": "guide",

                        "section": section[
                            "section"
                        ],

                        "subsection": section[
                            "subsection"
                        ],

                        "page": None,

                        "chunk_id": (
                            f"{library}_"
                            f"guide_"
                            f"{chunk_counter}"
                        )
                    }
                )
            )

            chunk_counter += 1

        # ----------------------------------------------------
        # Too large → recursively split
        # ----------------------------------------------------

        else:

            sub_chunks = (
                splitter.split_text(
                    content
                )
            )

            for sub_chunk in sub_chunks:

                sub_chunk = (
                    sub_chunk.strip()
                )

                if (
                    len(sub_chunk)
                    < MIN_CHUNK_SIZE
                ):
                    continue

                final_documents.append(
                    Document(
                        page_content=sub_chunk,

                        metadata={
                            "library": library,
                            "source": source,
                            "source_type": "guide",

                            "section": section[
                                "section"
                            ],

                            "subsection": section[
                                "subsection"
                            ],

                            "page": None,

                            "chunk_id": (
                                f"{library}_"
                                f"guide_"
                                f"{chunk_counter}"
                            )
                        }
                    )
                )

                chunk_counter += 1

    return final_documents


# ============================================================
# 11. PROCESS REFERENCE PDFs
# ============================================================

def process_reference(
    pages,
    library,
    source
):
    """
    Process large reference PDFs.

    Each PDF page is cleaned and then recursively split.

    Page metadata is preserved for citations.
    """

    final_documents = []

    chunk_counter = 0

    for page in pages:

        # ----------------------------------------------------
        # Extract text
        # ----------------------------------------------------

        text = clean_text(
            page.page_content
        )

        if not text:
            continue

        # ----------------------------------------------------
        # Remove obvious noise lines
        # ----------------------------------------------------

        lines = []

        for line in text.splitlines():

            line = line.strip()

            if is_noise(line):
                continue

            lines.append(line)

        text = "\n".join(
            lines
        ).strip()

        if not text:
            continue

        # ----------------------------------------------------
        # Remove consecutive duplicate lines
        # ----------------------------------------------------

        text = remove_duplicate_lines(
            text
        )

        if len(text) < MIN_CHUNK_SIZE:
            continue

        # ----------------------------------------------------
        # Human-readable page number
        # ----------------------------------------------------

        page_number = page.metadata.get(
            "page",
            1
        )

        # ----------------------------------------------------
        # Split page
        # ----------------------------------------------------

        page_chunks = (
            splitter.split_text(
                text
            )
        )

        for chunk_text in page_chunks:

            chunk_text = (
                chunk_text.strip()
            )

            # ------------------------------------------------
            # Remove tiny chunks
            # ------------------------------------------------

            if (
                len(chunk_text)
                < MIN_CHUNK_SIZE
            ):
                continue

            # ------------------------------------------------
            # Create document
            # ------------------------------------------------

            final_documents.append(
                Document(
                    page_content=chunk_text,

                    metadata={
                        "library": library,
                        "source": source,
                        "source_type": "reference",

                        "page": page_number,

                        "section": None,
                        "subsection": None,

                        "chunk_id": (
                            f"{library}_"
                            f"reference_"
                            f"{chunk_counter}"
                        )
                    }
                )
            )

            chunk_counter += 1

    return final_documents


# ============================================================
# 12. CREATE FINAL CHUNKS
# ============================================================

all_chunks = []

print()
print("=" * 80)
print("CREATING CHUNKS")
print("=" * 80)


for source, pages in pages_by_source.items():

    library = pages[0].metadata[
        "library"
    ]

    source_type = pages[0].metadata[
        "source_type"
    ]

    print()
    print("=" * 80)
    print(
        f"Processing: {source}"
    )
    print(
        f"Type: {source_type}"
    )
    print(
        f"Pages: {len(pages)}"
    )
    print("=" * 80)

    # --------------------------------------------------------
    # Guide
    # --------------------------------------------------------

    if source_type == "guide":

        chunks = process_guide(
            pages=pages,
            library=library,
            source=source
        )

    # --------------------------------------------------------
    # Reference
    # --------------------------------------------------------

    else:

        chunks = process_reference(
            pages=pages,
            library=library,
            source=source
        )

    all_chunks.extend(chunks)

    print(
        f"Created {len(chunks)} chunks"
    )


# ============================================================
# 13. REMOVE EXACT DUPLICATE CHUNKS
# ============================================================

print()
print("=" * 80)
print("REMOVING DUPLICATE CHUNKS")
print("=" * 80)


unique_chunks = []

seen = set()

duplicates_removed = 0

for chunk in all_chunks:

    # Normalize text for duplicate detection
    normalized_text = re.sub(
        r"\s+",
        " ",
        chunk.page_content
    ).strip().lower()

    duplicate_key = (
        chunk.metadata["library"],
        normalized_text
    )

    if duplicate_key in seen:

        duplicates_removed += 1
        continue

    seen.add(
        duplicate_key
    )

    unique_chunks.append(
        chunk
    )


all_chunks = unique_chunks


print(
    f"Duplicates removed: "
    f"{duplicates_removed}"
)

print(
    f"Unique chunks: "
    f"{len(all_chunks)}"
)


# ============================================================
# 14. REASSIGN GLOBAL CHUNK IDs
# ============================================================

for global_id, chunk in enumerate(
    all_chunks
):

    chunk.metadata[
        "global_chunk_id"
    ] = global_id


# ============================================================
# 15. FINAL STATISTICS
# ============================================================

print()
print("=" * 80)
print("FINAL DATASET STATISTICS")
print("=" * 80)


print(
    f"Total final chunks: "
    f"{len(all_chunks)}"
)


# ------------------------------------------------------------
# Chunks by source
# ------------------------------------------------------------

source_counts = Counter(
    chunk.metadata["source"]
    for chunk in all_chunks
)


print()
print("Chunks by source:")

for source, count in (
    source_counts.items()
):

    print(
        f"{source}: {count}"
    )


# ------------------------------------------------------------
# Chunk sizes
# ------------------------------------------------------------

if all_chunks:

    sizes = [
        len(chunk.page_content)
        for chunk in all_chunks
    ]

    print()
    print("Chunk size statistics:")

    print(
        f"Minimum: "
        f"{min(sizes)} characters"
    )

    print(
        f"Maximum: "
        f"{max(sizes)} characters"
    )

    print(
        f"Average: "
        f"{sum(sizes) / len(sizes):.0f} characters"
    )

    print(
        f"Median: "
        f"{sorted(sizes)[len(sizes)//2]} characters"
    )


# ============================================================
# 16. GUIDE CHUNK PREVIEW
# ============================================================

print()
print("=" * 100)
print("GUIDE CHUNK PREVIEW")
print("=" * 100)


guide_chunks = [
    chunk
    for chunk in all_chunks
    if chunk.metadata[
        "source_type"
    ] == "guide"
]


for chunk in guide_chunks[:10]:

    print()
    print("=" * 100)

    print(
        "Chunk ID:",
        chunk.metadata[
            "chunk_id"
        ]
    )

    print(
        "Global ID:",
        chunk.metadata[
            "global_chunk_id"
        ]
    )

    print(
        "Library:",
        chunk.metadata[
            "library"
        ]
    )

    print(
        "Section:",
        chunk.metadata.get(
            "section"
        )
    )

    print(
        "Subsection:",
        chunk.metadata.get(
            "subsection"
        )
    )

    print(
        "Characters:",
        len(
            chunk.page_content
        )
    )

    print()
    print("CONTENT:")
    print(
        chunk.page_content[:2000]
    )


# ============================================================
# 17. REFERENCE CHUNK PREVIEW
# ============================================================

print()
print("=" * 100)
print("REFERENCE CHUNK PREVIEW")
print("=" * 100)


reference_chunks = [
    chunk
    for chunk in all_chunks
    if chunk.metadata[
        "source_type"
    ] == "reference"
]


for chunk in reference_chunks[:5]:

    print()
    print("=" * 100)

    print(
        "Chunk ID:",
        chunk.metadata[
            "chunk_id"
        ]
    )

    print(
        "Global ID:",
        chunk.metadata[
            "global_chunk_id"
        ]
    )

    print(
        "Library:",
        chunk.metadata[
            "library"
        ]
    )

    print(
        "Source:",
        chunk.metadata[
            "source"
        ]
    )

    print(
        "Page:",
        chunk.metadata[
            "page"
        ]
    )

    print(
        "Characters:",
        len(
            chunk.page_content
        )
    )

    print()
    print("CONTENT:")
    print(
        chunk.page_content[:1500]
    )


# ============================================================
# 18. SAVE MARKDOWN FILES
# ============================================================

print()
print("=" * 80)
print("SAVING MARKDOWN FILES")
print("=" * 80)


for source in pages_by_source.keys():

    source_chunks = [
        chunk
        for chunk in all_chunks
        if chunk.metadata[
            "source"
        ] == source
    ]

    if not source_chunks:
        continue

    library = source_chunks[0].metadata[
        "library"
    ]

    output_file = (
        OUTPUT_FOLDER
        / f"{Path(source).stem}_chunks.md"
    )

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as f:

        f.write(
            f"# {library}\n\n"
        )

        f.write(
            f"Source: `{source}`\n\n"
        )

        f.write(
            f"Total chunks: "
            f"{len(source_chunks)}\n\n"
        )

        for chunk in source_chunks:

            f.write(
                f"## Chunk: "
                f"{chunk.metadata['chunk_id']}\n\n"
            )

            f.write(
                f"**Global ID:** "
                f"{chunk.metadata['global_chunk_id']}\n\n"
            )

            f.write(
                f"**Library:** "
                f"{chunk.metadata['library']}\n\n"
            )

            f.write(
                f"**Source:** "
                f"{chunk.metadata['source']}\n\n"
            )

            f.write(
                f"**Source Type:** "
                f"{chunk.metadata['source_type']}\n\n"
            )

            if chunk.metadata.get(
                "section"
            ):

                f.write(
                    f"**Section:** "
                    f"{chunk.metadata['section']}\n\n"
                )

            if chunk.metadata.get(
                "subsection"
            ):

                f.write(
                    f"**Subsection:** "
                    f"{chunk.metadata['subsection']}\n\n"
                )

            if chunk.metadata.get(
                "page"
            ) is not None:

                f.write(
                    f"**Page:** "
                    f"{chunk.metadata['page']}\n\n"
                )

            f.write(
                "### Content\n\n"
            )

            f.write(
                chunk.page_content
            )

            f.write(
                "\n\n---\n\n"
            )

    print(
        f"Saved: {output_file}"
    )


# ============================================================
# 19. SAVE JSONL
# ============================================================

jsonl_file = (
    OUTPUT_FOLDER
    / "all_chunks.jsonl"
)


with open(
    jsonl_file,
    "w",
    encoding="utf-8"
) as f:

    for chunk in all_chunks:

        record = {
            "chunk_id": chunk.metadata[
                "chunk_id"
            ],

            "global_chunk_id": chunk.metadata[
                "global_chunk_id"
            ],

            "text": chunk.page_content,

            "metadata": chunk.metadata
        }

        f.write(
            json.dumps(
                record,
                ensure_ascii=False
            )
            + "\n"
        )


print(
    f"Saved: {jsonl_file}"
)


# ============================================================
# 20. FINAL CHECK
# ============================================================

print()
print("=" * 80)
print("FINAL CHECK")
print("=" * 80)


tiny_chunks = [
    chunk
    for chunk in all_chunks
    if len(chunk.page_content)
    < MIN_CHUNK_SIZE
]


print(
    f"Chunks below {MIN_CHUNK_SIZE} chars: "
    f"{len(tiny_chunks)}"
)


if tiny_chunks:

    print(
        "WARNING: Tiny chunks still exist."
    )

else:

    print(
        "✓ No tiny chunks."
    )


print(
    f"Total chunks ready for embeddings: "
    f"{len(all_chunks)}"
)

print()
print(
    "Chunking stage completed successfully."
)

================================================================================
LOADING PDF FILES
================================================================================
Loading: NumPy_Complete_Guide.pdf
Loading: numpy-ref.pdf
Loading: pandas_complete_guide.pdf
Loading: scikit-learn-docs.pdf

Multiple definitions in dictionary at byte 0x2c4f47e for key /Author
Multiple definitions in dictionary at byte 0x2c4f486 for key /Title

================================================================================
TOTAL PDF PAGES LOADED: 4184
================================================================================

================================================================================
CREATING CHUNKS
================================================================================

================================================================================
Processing: NumPy_Complete_Guide.pdf
Type: guide
Pages: 12
================================================================================
Created 23 chunks

================================================================================
Processing: numpy-ref.pdf
Type: reference
Pages: 2101
================================================================================
Created 2265 chunks

================================================================================
Processing: pandas_complete_guide.pdf
Type: guide
Pages: 11
================================================================================
Created 19 chunks

================================================================================
Processing: scikit-learn-docs.pdf
Type: reference
Pages: 2060
================================================================================
Created 2299 chunks

================================================================================
REMOVING DUPLICATE CHUNKS
================================================================================
Duplicates removed: 0
Unique chunks: 4606

================================================================================
FINAL DATASET STATISTICS
================================================================================
Total final chunks: 4606

Chunks by source:
NumPy_Complete_Guide.pdf: 23
numpy-ref.pdf: 2265
pandas_complete_guide.pdf: 19
scikit-learn-docs.pdf: 2299

Chunk size statistics:
Minimum: 126 characters
Maximum: 2500 characters
Average: 1618 characters
Median: 1678 characters

====================================================================================================
GUIDE CHUNK PREVIEW
====================================================================================================

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_0
Global ID: 0
Library: NumPy_Complete_Guide
Section: None
Subsection: None
Characters: 299

CONTENT:
NumPy — The Complete Practical Guide
NumPy
The Complete Practical Guide
Arrays Indexing Broadcasting Math & Linear Algebra Statistics Random Sampling I/O
Performance
A reference document with runnable code examples for every core NumPy feature.
NumPy — The Complete Practical Guide
Table of Contents

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_1
Global ID: 1
Library: NumPy_Complete_Guide
Section: 1. Introduction to NumPy
Subsection: None
Characters: 937

CONTENT:
1. Introduction to NumPy
NumPy (Numerical Python) is the foundational package for numerical and scientific computing in Python. It
provides a fast, memory-efficient multidimensional array object called ndarray, along with a large library of
functions for operating on these arrays: mathematics, linear algebra, statistics, random number generation,
Fourier transforms, and more.
Why NumPy is used so widely:
Speed: Core operations are implemented in C, making them far faster than equivalent pure-Python
loops.
Memory efficiency: Arrays store homogeneous data in contiguous memory blocks, unlike Python lists.
Vectorization: Operations apply to whole arrays at once, removing the need for explicit loops.
Broadcasting: Arrays of different shapes can be combined in arithmetic operations without copying
data.
Foundation for the ecosystem: Pandas, SciPy, scikit-learn, TensorFlow, and PyTorch all build on
NumPy arrays or its conventions.

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_2
Global ID: 2
Library: NumPy_Complete_Guide
Section: 2. Installation and Import Convention
Subsection: None
Characters: 260

CONTENT:
2. Installation and Import Convention
Install NumPy with pip or conda:
pip install numpy
# or, with conda
conda install numpy
The universal convention is to import NumPy under the alias np:
import numpy as np
print(np.__version__) # check the installed version

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_3
Global ID: 3
Library: NumPy_Complete_Guide
Section: 3. The ndarray Object
Subsection: None
Characters: 755

CONTENT:
3. The ndarray Object
The core data structure in NumPy is the ndarray (N-dimensional array). Every ndarray has a fixed size, a
single data type (dtype) shared by all elements, and a shape describing its dimensions.
NumPy — The Complete Practical Guide
import numpy as np
a = np.array([1, 2, 3])
print(type(a)) # <class 'numpy.ndarray'>
print(a.ndim) # 1 -> number of dimensions
print(a.shape) # (3,) -> size along each dimension
print(a.dtype) # int64 (platform dependent)
print(a.size) # 3 -> total number of elements
Compared to a Python list, an ndarray is faster and uses less memory because it stores elements of the
same type in one contiguous block, letting NumPy use optimized, compiled loops instead of Python's
interpreter loop for each element.

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_4
Global ID: 4
Library: NumPy_Complete_Guide
Section: 4. Creating Arrays
Subsection: None
Characters: 1210

CONTENT:
4. Creating Arrays
4.1 From Python Lists / Tuples
a = np.array([1, 2, 3]) # 1-D array
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2-D array (2 rows, 3 cols)
c = np.array([1, 2, 3], dtype=np.float32) # specify dtype explicitly
4.2 Built-in Array Constructors
np.zeros((2, 3)) # 2x3 array of zeros
np.ones((3, 3)) # 3x3 array of ones
np.full((2, 2), 7) # 2x2 array filled with the value 7
np.empty((2, 3)) # uninitialized array (fast, garbage values)
np.eye(3) # 3x3 identity matrix
np.identity(4) # 4x4 identity matrix
np.diag([1, 2, 3]) # diagonal matrix from a 1-D array
4.3 Ranges and Sequences
np.arange(0, 10, 2) # array([0, 2, 4, 6, 8]) (like range())
np.linspace(0, 1, 5) # 5 evenly spaced values between 0 and 1
np.logspace(0, 3, 4) # array([1, 10, 100, 1000]) log-spaced values
4.4 Random Arrays
np.random.rand(2, 3) # uniform [0, 1), shape (2,3)
np.random.randn(2, 3) # standard normal distribution
np.random.randint(0, 10, 5) # 5 random ints in [0, 10)
4.5 Array-like Templates
NumPy — The Complete Practical Guide
x = np.array([[1, 2], [3, 4]])
np.zeros_like(x) # zeros with same shape/dtype as x
np.ones_like(x) # ones with same shape/dtype as x
np.full_like(x, 9) # filled with 9, same shape/dtype as x

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_5
Global ID: 5
Library: NumPy_Complete_Guide
Section: 5. Array Attributes
Subsection: None
Characters: 288

CONTENT:
5. Array Attributes
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape # (2, 3) - dimensions
a.ndim # 2 - number of axes
a.size # 6 - total elements
a.dtype # dtype('int64') - element data type
a.itemsize # 8 - bytes per element
a.nbytes # 48 - total bytes consumed
a.T # transpose of the array

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_6
Global ID: 6
Library: NumPy_Complete_Guide
Section: 6. Data Types (dtype)
Subsection: None
Characters: 448

CONTENT:
6. Data Types (dtype)
NumPy supports many numeric types beyond Python's built-in int and float, including fixed-width integers,
floats, complex numbers, and booleans.
np.array([1, 2, 3], dtype=np.int32)
np.array([1, 2, 3], dtype=np.float64)
np.array([1, 2, 3], dtype=np.bool_)
a = np.array([1.7, 2.3])
a.astype(np.int32) # cast to a different dtype -> array([1, 2])
Common dtypes: int8/16/32/64, uint8/16/32/64, float16/32/64, complex64/128, bool_.

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_7
Global ID: 7
Library: NumPy_Complete_Guide
Section: 7. Indexing and Slicing
Subsection: None
Characters: 463

CONTENT:
7. Indexing and Slicing
a = np.array([10, 20, 30, 40, 50])
a[0] # 10 - first element
a[-1] # 50 - last element
a[1:4] # [20 30 40] - slice
a[:3] # [10 20 30]
a[::2] # [10 30 50] - every second element
a[::-1] # [50 40 30 20 10] - reversed
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1, 2] # 6 - row 1, col 2
b[0] # [1 2 3] - entire first row
b[:, 1] # [2 5 8] - entire second column
b[0:2, 0:2] # top-left 2x2 sub-matrix
NumPy — The Complete Practical Guide

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_8
Global ID: 8
Library: NumPy_Complete_Guide
Section: 8. Boolean and Fancy Indexing
Subsection: None
Characters: 560

CONTENT:
8. Boolean and Fancy Indexing
8.1 Boolean Masking
a = np.array([1, 2, 3, 4, 5, 6])
mask = a > 3
print(mask) # [False False False True True True]
print(a[mask]) # [4 5 6]
a[a % 2 == 0] = 0 # set all even elements to 0
8.2 Fancy Indexing
a = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]
print(a[idx]) # [10 30 50]
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b[[0, 2]]) # rows 0 and 2 -> [[1 2] [5 6]]
8.3 np.where
a = np.array([1, 2, 3, 4, 5])
np.where(a > 2, a, 0) # array([0, 0, 3, 4, 5])
np.where(a > 2) # indices where condition is True: (array([2,3,4]),)

====================================================================================================
Chunk ID: NumPy_Complete_Guide_guide_9
Global ID: 9
Library: NumPy_Complete_Guide
Section: 9. Reshaping and Manipulating Arrays
Subsection: None
Characters: 488

CONTENT:
9. Reshaping and Manipulating Arrays
a = np.arange(12)
a.reshape(3, 4) # reshape into 3x4 (data unchanged, new view where possible)
a.reshape(3, -1) # -1 tells NumPy to infer that dimension
a.flatten() # returns a 1-D copy
a.ravel() # returns a 1-D view when possible (faster, no copy)
a.reshape(3,4).T # transpose
np.expand_dims(a, axis=0) # add a new axis -> shape (1, 12)
np.squeeze(a.reshape(1,12)) # remove axes of length 1 -> shape (12,)
a.reshape(3,4).swapaxes(0,1) # swap two axes

====================================================================================================
REFERENCE CHUNK PREVIEW
====================================================================================================

====================================================================================================
Chunk ID: numpy-ref_reference_0
Global ID: 23
Library: numpy-ref
Source: numpy-ref.pdf
Page: 3
Characters: 136

CONTENT:
CONTENTS
1 Python API 3
2 C API 1863
3 Other topics 1997
4 Acknowledgements 2041
Bibliography 2043
Python Module Index 2057
Index 2059
i

====================================================================================================
Chunk ID: numpy-ref_reference_1
Global ID: 24
Library: numpy-ref
Source: numpy-ref.pdf
Page: 5
Characters: 228

CONTENT:
NumPyReference,Release2.5.0
Release
2.5
Date
June28,2026
Thisreferencemanualdetailsfunctions,modules,andobjectsincludedinNumPy,describingwhattheyareandwhatthey
do. ForlearninghowtouseNumPy,seethecompletedocumentation.
CONTENTS 1

====================================================================================================
Chunk ID: numpy-ref_reference_2
Global ID: 25
Library: numpy-ref
Source: numpy-ref.pdf
Page: 7
Characters: 816

CONTENT:
CHAPTER
ONE
PYTHONAPI
1.1 NumPy’smodulestructure
NumPyhasalargenumberofsubmodules. MostregularusageofNumPyrequiresonlythemainnamespaceandasmaller
setofsubmodules. Theresteitherhavespecial-purposeornichenamespaces.
1.1.1 Mainnamespaces
Regular/recommendeduser-facingnamespacesforgeneraluse:
- numpy
- numpy.exceptions
- numpy.fft
- numpy.linalg
- numpy.polynomial
- numpy.random
- numpy.strings
- numpy.testing
- numpy.typing
1.1.2 Special-purposenamespaces
- numpy.ctypeslib-interactingwithNumPyobjectswith ctypes
- numpy.dtypes-dtypeclasses(typicallynotuseddirectlybyendusers)
- numpy.emath-mathematicalfunctionswithautomaticdomain
- numpy.lib-utilities&functionalitywhichdonotfitthemainnamespace
- numpy.rec-recordarrays(largelysupersededbydataframelibraries)
- numpy.version-smallmodulewithmoredetailedversioninfo

====================================================================================================
Chunk ID: numpy-ref_reference_3
Global ID: 26
Library: numpy-ref
Source: numpy-ref.pdf
Page: 8
Characters: 1555

CONTENT:
NumPyReference,Release2.5.0
1.1.3 Legacynamespaces
Prefer not to use these namespaces for new code. There are better alternatives and/or this code is deprecated or isn’t
reliable.
- numpy.char-legacystringfunctionality,onlyforfixed-widthstrings
- numpy.f2py-Fortranbindinggeneration(usuallyusedfromthecommandlineonly)
- numpy.ma-maskedarrays(notveryreliable,needsanoverhaul)
- numpy.matlib(pendingdeprecation)-functionssupporting matrixinstances
ExceptionsandWarnings
GeneralexceptionsusedbyNumPy. Notethatsomeexceptionsmaybemodulespecific,suchaslinearalgebraerrors.
NewinversionNumPy: 1.25
TheexceptionsmoduleisnewinNumPy1.25.
Warnings
ComplexWarning The warning raised when casting a complex dtype to a
realdtype.
VisibleDeprecationWarning Visibledeprecationwarning.
RankWarning Matrixrankwarning.
exception exceptions.ComplexWarning
Thewarningraisedwhencastingacomplexdtypetoarealdtype.
Asimplemented,castingacomplexnumbertoarealdiscardsitsimaginarypart,butthisbehaviormaynotbewhat
theuseractuallywants.
exception exceptions.VisibleDeprecationWarning
Visibledeprecationwarning.
By default, python will not show deprecation warnings, so this class can be used when a very visible warning is
helpful,forexamplebecausetheusageismostlikelyauserbug.
exception exceptions.RankWarning
Matrixrankwarning.
Issuedbypolynomialfunctionswhenthedesignmatrixisrankdeficient.
Exceptions
AxisError(axis[,ndim,msg_prefix]) Axissuppliedwasinvalid.
DTypePromotionError Multiple DTypes could not be converted to a comm

====================================================================================================
Chunk ID: numpy-ref_reference_4
Global ID: 27
Library: numpy-ref
Source: numpy-ref.pdf
Page: 9
Characters: 1682

CONTENT:
NumPyReference,Release2.5.0
exception exceptions.AxisError(axis, ndim=None, msg_prefix=None)
Axissuppliedwasinvalid.
This is raised whenever anaxis parameter is specified that is larger than the number of array dimensions. For
compatibilitywithcodewrittenagainstoldernumpyversions,whichraisedamixtureof ValueErrorand In-
dexErrorforthissituation,thisexceptionsubclassesbothtoensurethat except ValueError and except
IndexErrorstatementscontinuetocatch AxisError.
Parameters
axis
[intorstr]Theoutofboundsaxisoracustomexceptionmessage. Ifanaxisisprovided,then
ndimshouldbespecifiedaswell.
ndim
[int,optional]Thenumberofarraydimensions.
msg_prefix
[str,optional]Aprefixfortheexceptionmessage.
Attributes
axis
[int, optional]Theoutofboundsaxisor Noneifacustomexceptionmessagewasprovided.
This should be the axis as passed by the user, before any normalization to resolve negative
indices.
Newinversion1.22.
ndim
[int, optional] The number of array dimensions orNoneif a custom exception message was
provided.
Newinversion1.22.
Examples
>>> import numpy as np
>>> array_1d = np.arange(10)
>>> np.cumsum(array_1d, axis =1)
Traceback (most recent call last):
...
numpy.exceptions.AxisError: axis 1 is out of bounds for array of dimension 1
Negativeaxesarepreserved:
>>> np.cumsum(array_1d, axis =-2)
Traceback (most recent call last):
...
numpy.exceptions.AxisError: axis -2 is out of bounds for array of dimension 1
Theclassconstructorgenerallytakestheaxisandarrays’dimensionalityasarguments:
>>> print(np.e

================================================================================
SAVING MARKDOWN FILES
================================================================================
Saved: /kaggle/working/final_chunks/NumPy_Complete_Guide_chunks.md
Saved: /kaggle/working/final_chunks/numpy-ref_chunks.md
Saved: /kaggle/working/final_chunks/pandas_complete_guide_chunks.md
Saved: /kaggle/working/final_chunks/scikit-learn-docs_chunks.md
Saved: /kaggle/working/final_chunks/all_chunks.jsonl

================================================================================
FINAL CHECK
================================================================================
Chunks below 100 chars: 0
✓ No tiny chunks.
Total chunks ready for embeddings: 4606

Chunking stage completed successfully.

In [11]:
!pip install -q sentence-transformers faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 54.2 MB/s eta 0:00:0000:01:00:01

In [12]:
import pickle
import numpy as np
import torch
import faiss

from sentence_transformers import SentenceTransformer


CHUNKS_FILE = Path("/kaggle/working/final_chunks/all_chunks.jsonl")

VECTOR_FOLDER = Path("/kaggle/working/vector_store")

VECTOR_FOLDER.mkdir(
    parents=True,
    exist_ok=True)


if not CHUNKS_FILE.exists():

    raise FileNotFoundError(
        f"Chunks file not found:\n{CHUNKS_FILE}"
    )


print("=" * 80)
print("PYTHON DOCUMENTATION RAG - EMBEDDING STAGE")
print("=" * 80)
print(
    f"Chunks file: {CHUNKS_FILE}"
)

================================================================================
PYTHON DOCUMENTATION RAG - EMBEDDING STAGE
================================================================================
Chunks file: /kaggle/working/final_chunks/all_chunks.jsonl

In [13]:
chunks = []

with open(
    CHUNKS_FILE,
    "r",
    encoding="utf-8"
) as f:

    for line in f:

        line = line.strip()

        if not line:
            continue

        record = json.loads(line)

        chunks.append(record)


print()
print(f"Loaded chunks: {len(chunks)}")

if not chunks:
    raise ValueError("No chunks were loaded.")

print()
print("=" * 80)
print("EXAMPLE CHUNK")
print("=" * 80)

example = chunks[0]

print(
    "Chunk ID:",
    example["chunk_id"])

print("Library:",example["metadata"].get("library"))

print("Source:",example["metadata"].get("source"))

print("Page:",example["metadata"].get("page"))

print()
print(example["text"][:1000])

Loaded chunks: 4606

================================================================================
EXAMPLE CHUNK
================================================================================
Chunk ID: NumPy_Complete_Guide_guide_0
Library: NumPy_Complete_Guide
Source: NumPy_Complete_Guide.pdf
Page: None

NumPy — The Complete Practical Guide
NumPy
The Complete Practical Guide
Arrays Indexing Broadcasting Math & Linear Algebra Statistics Random Sampling I/O
Performance
A reference document with runnable code examples for every core NumPy feature.
NumPy — The Complete Practical Guide
Table of Contents

In [14]:
if torch.cuda.is_available():

    device = "cuda"

    print()
    print(
        "GPU detected:"
    )

    print(
        torch.cuda.get_device_name(0)
    )

else:

    device = "cpu"
    print()
    print("No GPU detected.")

    print("Using CPU.")


MODEL_NAME = (
    "BAAI/bge-small-en-v1.5"
)


print()
print("=" * 80)

print("LOADING EMBEDDING MODEL")
print("=" * 80)

print(f"Model: {MODEL_NAME}")

print(f"Device: {device}")


model = SentenceTransformer(
    MODEL_NAME,
    device=device
)

texts = [
    chunk["text"]
    for chunk in chunks
]


print()
print(f"Texts to embed: {len(texts)}")

GPU detected:
Tesla T4

================================================================================
LOADING EMBEDDING MODEL
================================================================================
Model: BAAI/bge-small-en-v1.5
Device: cuda

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Texts to embed: 4606

In [15]:
embeddings = model.encode(
    texts,
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True,
    device=device
)

print()

print("EMBEDDING INFORMATION")
print("=" * 80)

print("Shape:",embeddings.shape)

print("Data type:",embeddings.dtype)

print("Expected number of vectors:",len(chunks))

print("Embedding dimension:",embeddings.shape[1])

Batches:   0%|          | 0/144 [00:00<?, ?it/s]

EMBEDDING INFORMATION
================================================================================
Shape: (4606, 384)
Data type: float32
Expected number of vectors: 4606
Embedding dimension: 384

In [16]:
embeddings = np.asarray(
    embeddings,
    dtype="float32"
)

print()
print("BUILDING FAISS INDEX")
print("=" * 80)

embedding_dimension = (embeddings.shape[1])

BUILDING FAISS INDEX
================================================================================

In [17]:
index = faiss.IndexFlatIP(embedding_dimension)
index.add(embeddings)

print(
    f"FAISS vectors stored: "
    f"{index.ntotal}"
)

print(
    f"Vector dimension: "
    f"{embedding_dimension}")


INDEX_FILE = (
    VECTOR_FOLDER
    / "python_docs.faiss")


faiss.write_index(index,str(INDEX_FILE))


print()
print(f"FAISS index saved to:")
print(INDEX_FILE)

FAISS vectors stored: 4606
Vector dimension: 384

FAISS index saved to:
/kaggle/working/vector_store/python_docs.faiss

In [18]:
METADATA_FILE = (
    VECTOR_FOLDER
    / "chunk_metadata.pkl")

with open(
    METADATA_FILE,
    "wb"
) as f:
    pickle.dump(chunks,f)


print()
print("Chunk metadata saved to:")
print(METADATA_FILE)

EMBEDDINGS_FILE = (
    VECTOR_FOLDER
    / "embeddings.npy")

np.save(
    EMBEDDINGS_FILE,
    embeddings
)


print()
print("Embeddings saved to:")
print(EMBEDDINGS_FILE)

Chunk metadata saved to:
/kaggle/working/vector_store/chunk_metadata.pkl

Embeddings saved to:
/kaggle/working/vector_store/embeddings.npy

In [19]:
print("Summary")
print()
print(f"Total chunks:       {len(chunks)}")

print(f"Embedding dimension: {embedding_dimension}")

print(f"FAISS vectors:       {index.ntotal}")

print(f"Model:               {MODEL_NAME}")

print(f"Device:              {device}")

print()
print("Files created:")

print(f"1. {INDEX_FILE}")

print(f"2. {METADATA_FILE}")

print(f"3. {EMBEDDINGS_FILE}")

Summary

Total chunks:       4606
Embedding dimension: 384
FAISS vectors:       4606
Model:               BAAI/bge-small-en-v1.5
Device:              cuda

Files created:
1. /kaggle/working/vector_store/python_docs.faiss
2. /kaggle/working/vector_store/chunk_metadata.pkl
3. /kaggle/working/vector_store/embeddings.npy

In [20]:
import faiss
import pickle
import numpy as np

FAISS_PATH = (
    "/kaggle/working/vector_store/"
    "python_docs.faiss"
)

METADATA_PATH = (
    "/kaggle/working/vector_store/"
    "chunk_metadata.pkl"
)

EMBEDDINGS_PATH = (
    "/kaggle/working/vector_store/"
    "embeddings.npy"
)

index = faiss.read_index(
    FAISS_PATH
)

with open(
    METADATA_PATH,
    "rb"
) as f:

    chunk_metadata = pickle.load(f)

embeddings = np.load(
    EMBEDDINGS_PATH
)

print("FAISS vectors:", index.ntotal)
print("Metadata:", len(chunk_metadata))
print("Embeddings:", embeddings.shape)

FAISS vectors: 4606
Metadata: 4606
Embeddings: (4606, 384)

# **Retrieval**

In [21]:
from sentence_transformers import SentenceTransformer
import torch

EMBEDDING_MODEL_NAME = (
    "BAAI/bge-small-en-v1.5"
)

embedding_model = SentenceTransformer(
    EMBEDDING_MODEL_NAME,
    device=(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )
)

print("Embedding model loaded")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: BAAI/bge-small-en-v1.5
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Embedding model loaded

In [22]:
def faiss_search(
    query,
    top_k=5
):
    # 1. Create query embedding
    query_embedding = embedding_model.encode(
        [query],
        normalize_embeddings=True
    )
    query_embedding = np.asarray(
        query_embedding,
        dtype="float32"
    )

    # 2. Search FAISS

    scores, indices = index.search(
        query_embedding,
        top_k
    )
    # 3. Build results

    results = []


    for rank, (score, idx) in enumerate(
        zip(scores[0], indices[0]),
        start=1
    ):

        # Skip invalid FAISS indices
        if idx < 0:
            continue

        metadata = chunk_metadata[idx]

        # Extract text

        text = metadata.get(
            "text",
            ""
        )
        # Store result

        results.append({

            "rank": rank,
            "index": int(idx),
            "score": float(score),
            "text": text,
            "metadata": metadata

        })
    return results

In [23]:
query = "How do I create a NumPy array?"

results = faiss_search(
    query,
    top_k=10
)

print("QUERY:")
print(query)

for result in results:

    print("\n" + "=" * 80)

    print("Rank:", result["rank"])
    print(
        "FAISS score:",
        round(result["score"], 4)
    )

    print(
        "Library:",
        result["metadata"].get("library")
    )

    print("\nCONTENT:")
    print(
        result["text"][:800]
    )

QUERY:
How do I create a NumPy array?

================================================================================
Rank: 1
FAISS score: 0.8252
Library: None

CONTENT:
4. Creating Arrays
4.1 From Python Lists / Tuples
a = np.array([1, 2, 3]) # 1-D array
b = np.array([[1, 2, 3], [4, 5, 6]]) # 2-D array (2 rows, 3 cols)
c = np.array([1, 2, 3], dtype=np.float32) # specify dtype explicitly
4.2 Built-in Array Constructors
np.zeros((2, 3)) # 2x3 array of zeros
np.ones((3, 3)) # 3x3 array of ones
np.full((2, 2), 7) # 2x2 array filled with the value 7
np.empty((2, 3)) # uninitialized array (fast, garbage values)
np.eye(3) # 3x3 identity matrix
np.identity(4) # 4x4 identity matrix
np.diag([1, 2, 3]) # diagonal matrix from a 1-D array
4.3 Ranges and Sequences
np.arange(0, 10, 2) # array([0, 2, 4, 6, 8]) (like range())
np.linspace(0, 1, 5) # 5 evenly spaced values between 0 and 1
np.logspace(0, 3, 4) # array([1, 10, 100, 1000]) log-spaced values
4.4 Random Arrays
n

================================================================================
Rank: 2
FAISS score: 0.784
Library: None

CONTENT:
NumPyReference,Release2.5.0
Notes
Thisconstructorcanbecomparedto empty: itcreatesanewrecordarraybutdoesnotfillitwithdata. Tocreate
arecordarrayfromdata,useoneofthefollowingmethods:
1. Createastandardndarrayandconvertittoarecordarray,using arr.view(np.recarray)
2. Usethe bufkeyword.
3. Use np.rec.fromrecords.
Examples
Createanarraywithtwofields, xand y:
>>> import numpy as np
>>> x = np.array([(1.0, 2), ( 3.0, 4)], dtype =[('x', '<f8'), ( 'y', '<i8')])
>>> x
array([(1., 2), (3., 4)], dtype=[('x', '<f8'), ('y', '<i8')])
>>> x['x']
array([1., 3.])
Viewthearrayasarecordarray:
>>> x = x.view(np.recarray)
>>> x.x
array([1., 3.])
>>> x.y
array([2, 4])
Createanew,emptyrecordarray:
>>> np.recarray((2,),
... dtype=[('x', int), ( 'y', float), ( 'z', int)])
rec.array([(-1073741821, 1.2249118382103472e

================================================================================
Rank: 3
FAISS score: 0.7837
Library: None

CONTENT:
NumPyReference,Release2.5.0
Examples
>>> import numpy as np
>>> a = np.array([[1, 2], [ 3, 4]])
>>> a
array([[1, 2],
[3, 4]])
>>> a.transpose()
array([[1, 3],
[2, 4]])
>>> a.transpose((1, 0))
array([[1, 3],
[2, 4]])
>>> a.transpose(1, 0)
array([[1, 3],
[2, 4]])
>>> a = np.array([1, 2, 3, 4])
>>> a
array([1, 2, 3, 4])
>>> a.transpose()
array([1, 2, 3, 4])
Changingthenumberofdimensions
ma.atleast_1d(*arys) Convertinputstoarrayswithatleastonedimension.
ma.atleast_2d(*arys) Viewinputsasarrayswithatleasttwodimensions.
ma.atleast_3d(*arys) Viewinputsasarrayswithatleastthreedimensions.
ma.expand_dims(a,axis) Expandtheshapeofanarray.
ma.squeeze(a[,axis,fill_value,hardmask]) Removeaxesoflengthonefrom a.
ma.MaskedArray.squeeze([axis]) Removeaxesoflengthonefrom a.
ma.stack(arrays[,axis,out,dtype,cast

================================================================================
Rank: 4
FAISS score: 0.779
Library: None

CONTENT:
NumPyReference,Release2.5.0
Creatingrecordarrays
Note: Pleasereferto Record arraysforrecordarrays.
rec.array(obj[,dtype,shape,offset,...]) Constructarecordarrayfromawide-varietyofobjects.
rec.fromarrays(arrayList[,dtype,shape,...]) Createarecordarrayfroma(flat)listofarrays
rec.fromrecords(recList[,dtype,shape,...]) Createarecarrayfromalistofrecordsintextform.
rec.fromstring(datastring[,dtype,shape,...]) Createarecordarrayfrombinarydata
rec.fromfile(fd[,dtype,shape,offset,...]) Createanarrayfrombinaryfiledata
Creatingcharacterarrays( numpy.char)
Note: numpy.charisusedtocreatecharacterarrays.
char.array(obj[,itemsize,copy,unicode,order]) Createa chararray.
char.asarray(obj[,itemsize,unicode,order]) Convert the input to achararray, copying the data
onlyifnecessary.
Numericalranges
arange([sta

================================================================================
Rank: 5
FAISS score: 0.7781
Library: None

CONTENT:
NumPyReference,Release2.5.0
Examples
>>> import numpy as np
>>> rng = np.random.default_rng()
>>> arrays = [rng.normal(size=(3,4)) for _ in range(10)]
>>> np.stack(arrays, axis =0).shape
(10, 3, 4)
>>> np.stack(arrays, axis =1).shape
(3, 10, 4)
>>> np.stack(arrays, axis =2).shape
(3, 4, 10)
>>> a = np.array([1, 2, 3])
>>> b = np.array([4, 5, 6])
>>> np.stack((a, b))
array([[1, 2, 3],
[4, 5, 6]])
>>> np.stack((a, b), axis =-1)
array([[1, 4],
[2, 5],
[3, 6]])
numpy.block(arrays)
Assembleannd-arrayfromnestedlistsofblocks.
Blocksintheinnermostlistsareconcatenated(see concatenate)alongthelastdimension(-1),thentheseare
concatenatedalongthesecond-lastdimension(-2),andsoonuntiltheoutermostlistisreached.
Blocks canbe ofany dimension, butwillnot be broadcasted usingthe normalrules. Instead, leadinga

================================================================================
Rank: 6
FAISS score: 0.7763
Library: None

CONTENT:
NumPyReference,Release2.5.0
Notes
This function is the preferred method for creating an array copy. The functionnumpy.copy is similar, but it
defaultstousingorder‘K’,andwillnotpasssub-classesthroughbydefault.
Examples
>>> import numpy as np
>>> x = np.array([[1,2,3],[4,5,6]], order ='F')
>>> y = x.copy()
>>> x.fill(0)
>>> x
array([[0, 0, 0],
[0, 0, 0]])
>>> y
array([[1, 2, 3],
[4, 5, 6]])
>>> y.flags['C_CONTIGUOUS']
True
ForarrayscontainingPythonobjects(e.g. dtype=np.object_),thecopyisashallowone. Thenewarraywillcontain
thesameobjectwhichmayleadtosurprisesifthatobjectcanbemodified(ismutable):
>>> a = np.array([1, 'm', [ 2, 3, 4]], dtype =np.object_)
>>> b = a.copy()
>>> b[2][0] = 10
>>> a
array([1, 'm', list([10, 3, 4])], dtype=object)
Toensureallelementswithinan objectarrayarecopied,use c

================================================================================
Rank: 7
FAISS score: 0.7734
Library: None

CONTENT:
7. Indexing and Slicing
a = np.array([10, 20, 30, 40, 50])
a[0] # 10 - first element
a[-1] # 50 - last element
a[1:4] # [20 30 40] - slice
a[:3] # [10 20 30]
a[::2] # [10 30 50] - every second element
a[::-1] # [50 40 30 20 10] - reversed
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b[1, 2] # 6 - row 1, col 2
b[0] # [1 2 3] - entire first row
b[:, 1] # [2 5 8] - entire second column
b[0:2, 0:2] # top-left 2x2 sub-matrix
NumPy — The Complete Practical Guide

================================================================================
Rank: 8
FAISS score: 0.7721
Library: None

CONTENT:
10. Joining and Splitting Arrays
10.1 Joining
NumPy — The Complete Practical Guide
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a, b]) # [1 2 3 4 5 6]
np.stack([a, b]) # new axis -> [[1 2 3] [4 5 6]]
np.vstack([a, b]) # stack vertically (row-wise)
np.hstack([a, b]) # stack horizontally (column-wise for 1-D)
np.column_stack([a, b]) # stack as columns -> shape (3, 2)
10.2 Splitting
a = np.arange(9)
np.split(a, 3) # 3 equal parts: [array([0,1,2]), array([3,4,5]), array([6,7,8])]
np.array_split(a, 4) # split into 4 uneven parts if not evenly divisible
b = np.arange(16).reshape(4, 4)
np.hsplit(b, 2) # split into 2 along columns
np.vsplit(b, 2) # split into 2 along rows

================================================================================
Rank: 9
FAISS score: 0.7673
Library: None

CONTENT:
20. File I/O
a = np.array([[1, 2, 3], [4, 5, 6]])
# NumPy's own binary format (fast, preserves dtype/shape exactly)
np.save('array.npy', a)
loaded = np.load('array.npy')
# Multiple arrays in one compressed file
np.savez('arrays.npz', x=a, y=a * 2)
data = np.load('arrays.npz')
data['x']; data['y']
# Plain text formats
np.savetxt('array.csv', a, delimiter=',')
loaded_csv = np.loadtxt('array.csv', delimiter=',')
genfromtxt_result = np.genfromtxt('array.csv', delimiter=',') # handles missing values

================================================================================
Rank: 10
FAISS score: 0.7672
Library: None

CONTENT:
NumPyReference,Release2.5.0
Examples
>>> import numpy as np
>>> import ctypes
>>> x = np.array([[0, 1], [ 2, 3]], dtype =np.int32)
>>> x
array([[0, 1],
[2, 3]], dtype=int32)
>>> x.ctypes.data
31962608 # may vary
>>> x.ctypes.data_as(ctypes.POINTER(ctypes.c_uint32))
<__main__.LP_c_uint object at 0x7ff2fc1fc200> # may vary
>>> x.ctypes.data_as(ctypes.POINTER(ctypes.c_uint32)).contents
c_uint(0)
>>> x.ctypes.data_as(ctypes.POINTER(ctypes.c_uint64)).contents
c_ulong(4294967296)
>>> x.ctypes.shape
<numpy._core._internal.c_long_Array_2 object at 0x7ff2fc1fce60> # may vary
>>> x.ctypes.strides
<numpy._core._internal.c_long_Array_2 object at 0x7ff2fc1ff320> # may vary
Arraymethods
An ndarrayobjecthasmanymethodswhichoperateonorwiththearrayinsomefashion,typicallyreturninganarray
result. Thesemethods

In [27]:
!pip install -q sentence-transformers

In [24]:
from sentence_transformers import CrossEncoder

RERANKER_NAME = (
    "cross-encoder/ms-marco-MiniLM-L-6-v2"
)

reranker = CrossEncoder(
    RERANKER_NAME,
    device=(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )
)

print("Reranker loaded")

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

Reranker loaded

In [25]:
def rerank_results(
    query,
    results,
    top_k=5
):

    pairs = [
        (
            query,
            result["text"]
        )
        for result in results
    ]

    scores = reranker.predict(
        pairs
    )

    for result, score in zip(
        results,
        scores
    ):

        result["rerank_score"] = float(
            score
        )

    results = sorted(
        results,
        key=lambda x: x["rerank_score"],
        reverse=True
    )

    for rank, result in enumerate(
        results[:top_k],
        start=1
    ):

        result["rerank_rank"] = rank

    return results[:top_k]

In [26]:
query = "How do I create a NumPy array?"

candidates = faiss_search(
    query,
    top_k=20
)

final_results = rerank_results(
    query,
    candidates,
    top_k=5
)

for result in final_results:

    print("\n" + "=" * 80)

    print(
        "Rerank:",
        result["rerank_rank"]
    )

    print(
        "FAISS score:",
        round(result["score"], 4)
    )

    print(
        "Reranker score:",
        round(
            result["rerank_score"],
            4
        )
    )

    print(
        "Library:",
        result["metadata"].get(
            "library"
        )
    )

    print("\n", result["text"][:1000])

================================================================================
Rerank: 1
FAISS score: 0.7763
Reranker score: 4.6015
Library: None

 NumPyReference,Release2.5.0
Notes
This function is the preferred method for creating an array copy. The functionnumpy.copy is similar, but it
defaultstousingorder‘K’,andwillnotpasssub-classesthroughbydefault.
Examples
>>> import numpy as np
>>> x = np.array([[1,2,3],[4,5,6]], order ='F')
>>> y = x.copy()
>>> x.fill(0)
>>> x
array([[0, 0, 0],
[0, 0, 0]])
>>> y
array([[1, 2, 3],
[4, 5, 6]])
>>> y.flags['C_CONTIGUOUS']
True
ForarrayscontainingPythonobjects(e.g. dtype=np.object_),thecopyisashallowone. Thenewarraywillcontain
thesameobjectwhichmayleadtosurprisesifthatobjectcanbemodified(ismutable):
>>> a = np.array([1, 'm', [ 2, 3, 4]], dtype =np.object_)
>>> b = a.copy()
>>> b[2][0] = 10
>>> a
array([1, 'm', list([10, 3, 4])], dtype=object)
Toensureallelementswithinan objectarrayarecopied,use copy.deepcopy:
>>> import copy
>>> a = np.array([1, 'm', [ 2, 3, 4]], dtype =np.object_)
>>> c = copy.deepcopy(a)
>>> c[2][0] = 10
>>> c
array([1, 'm', list([10, 3, 4])], dtype=object)
>>> a
array([1,

================================================================================
Rerank: 2
FAISS score: 0.784
Reranker score: 3.6468
Library: None

 NumPyReference,Release2.5.0
Notes
Thisconstructorcanbecomparedto empty: itcreatesanewrecordarraybutdoesnotfillitwithdata. Tocreate
arecordarrayfromdata,useoneofthefollowingmethods:
1. Createastandardndarrayandconvertittoarecordarray,using arr.view(np.recarray)
2. Usethe bufkeyword.
3. Use np.rec.fromrecords.
Examples
Createanarraywithtwofields, xand y:
>>> import numpy as np
>>> x = np.array([(1.0, 2), ( 3.0, 4)], dtype =[('x', '<f8'), ( 'y', '<i8')])
>>> x
array([(1., 2), (3., 4)], dtype=[('x', '<f8'), ('y', '<i8')])
>>> x['x']
array([1., 3.])
Viewthearrayasarecordarray:
>>> x = x.view(np.recarray)
>>> x.x
array([1., 3.])
>>> x.y
array([2, 4])
Createanew,emptyrecordarray:
>>> np.recarray((2,),
... dtype=[('x', int), ( 'y', float), ( 'z', int)])
rec.array([(-1073741821, 1.2249118382103472e-301, 24547520),
(3471280, 1.2134086255804012e-316, 0)],
dtype=[('x', '<i4'), ('y', '<f8'), ('z', '<i4')])
class numpy.record(length_or_data, /, dtype=None)
Adata-typescalarthatallowsfieldaccessasattr

================================================================================
Rerank: 3
FAISS score: 0.7646
Reranker score: 3.4729
Library: None

 NumPyReference,Release2.5.0
Examples
>>> import numpy as np
>>> x = np.array([(-1, 2)], dtype =[('a', np .int8), ( 'b', np .int8)])
Viewingarraydatausingadifferenttypeanddtype:
>>> nonneg = np.dtype([("a", np .uint8), ( "b", np .uint8)])
>>> y = x.view(dtype=nonneg, type=np.recarray)
>>> x["a"]
array([-1], dtype=int8)
>>> y.a
array([255], dtype=uint8)
Creatingaviewonastructuredarraysoitcanbeusedincalculations
>>> x = np.array([(1, 2),(3,4)], dtype =[('a', np .int8), ( 'b', np .int8)])
>>> xv = x.view(dtype=np.int8).reshape(-1,2)
>>> xv
array([[1, 2],
[3, 4]], dtype=int8)
>>> xv.mean(0)
array([2., 3.])
Makingchangestotheviewchangestheunderlyingarray
>>> xv[0,1] = 20
>>> x
array([(1, 20), (3, 4)], dtype=[('a', 'i1'), ('b', 'i1')])
Usingaviewtoconvertanarraytoarecarray:
>>> z = x.view(np.recarray)
>>> z.a
array([1, 3], dtype=int8)
Viewssharedata:
>>> x[0] = (9, 10)
>>> z[0]
np.record((9, 10), dtype=[('a', 'i1'), ('b', 'i1')])
Views that change the dtype size (bytes per entry) should norma

================================================================================
Rerank: 4
FAISS score: 0.7646
Reranker score: 3.4729
Library: None

 NumPyReference,Release2.5.0
Examples
>>> import numpy as np
>>> x = np.array([(-1, 2)], dtype =[('a', np .int8), ( 'b', np .int8)])
Viewingarraydatausingadifferenttypeanddtype:
>>> nonneg = np.dtype([("a", np .uint8), ( "b", np .uint8)])
>>> y = x.view(dtype=nonneg, type=np.recarray)
>>> x["a"]
array([-1], dtype=int8)
>>> y.a
array([255], dtype=uint8)
Creatingaviewonastructuredarraysoitcanbeusedincalculations
>>> x = np.array([(1, 2),(3,4)], dtype =[('a', np .int8), ( 'b', np .int8)])
>>> xv = x.view(dtype=np.int8).reshape(-1,2)
>>> xv
array([[1, 2],
[3, 4]], dtype=int8)
>>> xv.mean(0)
array([2., 3.])
Makingchangestotheviewchangestheunderlyingarray
>>> xv[0,1] = 20
>>> x
array([(1, 20), (3, 4)], dtype=[('a', 'i1'), ('b', 'i1')])
Usingaviewtoconvertanarraytoarecarray:
>>> z = x.view(np.recarray)
>>> z.a
array([1, 3], dtype=int8)
Viewssharedata:
>>> x[0] = (9, 10)
>>> z[0]
np.record((9, 10), dtype=[('a', 'i1'), ('b', 'i1')])
Views that change the dtype size (bytes per entry) should norma

================================================================================
Rerank: 5
FAISS score: 0.7593
Reranker score: 3.0577
Library: None

 NumPyReference,Release2.5.0
(continuedfrompreviouspage)
[ 0, 0, 255]],
[[ 0, 0, 255],
[ 0, 0, 255]]])
Fromexistingdata
array(object[,dtype,copy,order,subok,...]) Createanarray.
asarray(a[,dtype,order,device,copy,like]) Converttheinputtoanarray.
asanyarray(a[,dtype,order,device,copy,like]) Convert the input to an ndarray, but pass ndarray sub-
classesthrough.
ascontiguousarray(a[,dtype,like]) Returnacontiguousarray(ndim>=1)inmemory(Cor-
der).
asmatrix(data[,dtype]) Interprettheinputasamatrix.
astype(x,dtype,/,*[,copy,device]) Copiesanarraytoaspecifieddatatype.
copy(a[,order,subok]) Returnanarraycopyofthegivenobject.
frombuffer(buffer[,dtype,count,offset,like]) Interpretabufferasa1-dimensionalarray.
from_dlpack(x,/,*[,device,copy]) Create a NumPy array from an object implementing the
__dlpack__protocol.
fromfile(file[,dtype,count,sep,offset,like]) Constructanarrayfromdatainatextorbinaryfile.
fromfunction(function,shape,*[,dtype,like]) Constructanarraybyexecutingafunctionovereachco-
ordin

In [27]:
!pip install -q -U google-genai python-dotenv

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 kB 828.7 kB/s eta 0:00:00 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.2/110.2 kB 1.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 9.3 MB/s eta 0:00:00:00:010:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.7/259.7 kB 17.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 472.6/472.6 kB 27.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 29.3 MB/s eta 0:00:0000:0100:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.39.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-adk 1.29.0 requires google-cloud-bigquery-storage>=2.0.0, which is not installed.
google-colab 1.0.0 requires google-auth==2.47.0, but you have google-auth 2.57.0 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.14.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.3.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
google-cloud-aiplatform 1.148.1 requires google-genai<2.0.0,>=1.66.0; python_version >= "3.10", but you have google-genai 2.20.0 which is incompatible.
google-adk 1.29.0 requires google-genai<2.0.0,>=1.64.0, but you have google-genai 2.20.0 which is incompatible.
gradio 5.50.0 requires pydantic<=2.12.3,>=2.0, but you have pydantic 2.13.5 which is incompatible.

In [29]:
!pip install groq

Collecting groq
  Downloading groq-1.7.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.13.5)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.13)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.7.0-py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 1.2 MB/s eta 0:00:00a 0:00:01
Installing collected packages: groq
Successfully installed groq-1.7.0

In [30]:
from dotenv import load_dotenv
from groq import Groq
import os

load_dotenv(
    "/kaggle/working/.env",
    override=True
)

API_KEY = os.getenv("GROQ_API_KEY")

ROUTER_MODEL = os.getenv("GROQ_MODEL")
GENERATION_MODEL = os.getenv("GROQ_MODEL")

print("API key loaded:", bool(API_KEY))
print("Router:", ROUTER_MODEL)
print("Generator:", GENERATION_MODEL)

client = Groq(
    api_key=API_KEY
)

print("Groq client ready")

API key loaded: True
Router: openai/gpt-oss-20b
Generator: openai/gpt-oss-20b
Groq client ready

In [59]:
#response = client.chat.completions.create(
#    model=GENERATION_MODEL,
#    messages=[
#        {
#            "role": "user",
#            "content": "What is a NumPy array? Answer in one sentence."
#        }
#    ]
#)
#
#print(response.choices[0].message.content)

A NumPy array is a homogeneous, multi‑dimensional container that stores data in a contiguous block of memory for fast numerical operations.

In [31]:
# QUERY ROUTER

def route_query(query):

    prompt = f"""
You are a query router for a Python documentation assistant.

The system has a RAG knowledge base containing documentation
for exactly these libraries:

- NumPy
- Pandas
- Scikit-learn

Classify the user's question into EXACTLY ONE of these
three categories:

============================================================
1. RETRIEVE
============================================================

Choose RETRIEVE when the question is specifically about:

- NumPy
- Pandas
- Scikit-learn
- Their functions
- Their classes
- Their APIs
- Their usage
- Their parameters
- Their behavior
- Their examples
- Their errors
- Their documentation

Examples:

"How do I create a NumPy array?"
RETRIEVE

"How does pandas merge work?"
RETRIEVE

"What parameters does sklearn train_test_split accept?"
RETRIEVE

"How can I normalize data using scikit-learn?"
RETRIEVE


============================================================
2. GENERAL
============================================================

Choose GENERAL when the question is about Python itself
or general programming concepts, but is NOT specifically
about NumPy, Pandas, or Scikit-learn.

Examples:

"What is a Python list?"
GENERAL

"What is a tuple in Python?"
GENERAL

"How do Python decorators work?"
GENERAL

"What is a Python dictionary?"
GENERAL

"How does a for loop work in Python?"
GENERAL

"What is object-oriented programming?"
GENERAL


============================================================
3. OUT_OF_CONTEXT
============================================================

Choose OUT_OF_CONTEXT when the question is unrelated to:

- Python
- Programming
- NumPy
- Pandas
- Scikit-learn

Examples:

"What is the capital of France?"
OUT_OF_CONTEXT

"Who won the football match?"
OUT_OF_CONTEXT

"Tell me a joke."
OUT_OF_CONTEXT

"What is the weather today?"
OUT_OF_CONTEXT

"How do I cook pasta?"
OUT_OF_CONTEXT


============================================================
IMPORTANT RULES
============================================================

A question about NumPy, Pandas, or Scikit-learn MUST be
RETRIEVE even if it is also a Python question.

A general Python question that does not require the
NumPy/Pandas/Scikit-learn documentation is GENERAL.

A completely unrelated question is OUT_OF_CONTEXT.

Return ONLY ONE of:

RETRIEVE
GENERAL
OUT_OF_CONTEXT

Do not return explanations.
Do not return punctuation.
Do not return anything else.

User question:
{query}
"""

    response = client.chat.completions.create(
        model=ROUTER_MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    route = response.choices[0].message.content.strip().upper()

    valid_routes = {
        "RETRIEVE",
        "GENERAL",
        "OUT_OF_CONTEXT"
    }

    if route not in valid_routes:
        route = "OUT_OF_CONTEXT"

    return route

In [32]:
#test_queries = [
#
#    "How do I create a NumPy array?",
#
#    "How do I merge two pandas DataFrames?",
#
#    "What is train_test_split in scikit-learn?",
#
#    "What is a Python list?",
#
#    "How do Python decorators work?",
#
#    "What is a dictionary in Python?",
#
#    "What is the capital of France?",
#
#    "Tell me a joke."
#]
#
#for query in test_queries:
#
#    route = route_query(query)
#
#    print("=" * 80)
#    print("Query:", query)
#    print("Route:", route)

================================================================================
Query: How do I create a NumPy array?
Route: RETRIEVE

In [33]:
PYTHON_DOCS_URL = "https://docs.python.org/3/"


def general_answer(query):

    return (
        "For general Python documentation, visit the official "
        "Python documentation:\n"
        f"{PYTHON_DOCS_URL}"
    )

In [34]:
def out_of_context_answer():

    return "This question is out of context."

In [35]:
def build_context(results):

    context_parts = []

    for i, result in enumerate(
        results,
        start=1
    ):

        metadata = result["metadata"]

        library = metadata.get(
            "library",
            "Unknown"
        )

        source = metadata.get(
            "source",
            "Unknown"
        )

        page = metadata.get(
            "page",
            None
        )

        header = (
            f"[Document {i}]\n"
            f"Library: {library}\n"
            f"Source: {source}\n"
        )

        if page is not None:

            header += (
                f"Page: {page}\n"
            )

        context_parts.append(
            header
            + "\n"
            + result["text"]
        )

    return "\n\n".join(
        context_parts
    )

In [36]:
def rag_answer(query, context):

    prompt = f"""
You are a Python documentation assistant.

Your knowledge source for this answer is ONLY the
documentation provided below.

The documentation comes from:

- NumPy
- Pandas
- Scikit-learn

Answer the user's question using ONLY the provided context.

Do NOT use outside knowledge.

Do NOT invent information.

If the provided context does not contain enough information
to answer the question, say:

"I don't know based on the provided documentation."

Keep the answer clear and concise.

============================================================
DOCUMENTATION CONTEXT
============================================================

{context}

============================================================
USER QUESTION
============================================================

{query}

============================================================
ANSWER
============================================================
"""

    response = client.chat.completions.create(
        model=GENERATION_MODEL,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()

In [37]:
def answer_query(query):
    # 1. ROUTE THE QUERY

    route = route_query(query)

    print("Route:", route)

    # 2. RETRIEVE
    if route == "RETRIEVE":

        # FAISS search
        results = faiss_search(
            query,
            top_k=5
        )
        # Build context

        context_parts = []

        for result in results:

            text = result.get("text", "")

            if text:
                context_parts.append(text)

        context = "\n\n---\n\n".join(
            context_parts
        )

        # Generate answer

        answer = rag_answer(
            query,
            context
        )

        return {
            "route": "RETRIEVE",
            "answer": answer,
            "results": results
        }

    # 3. GENERAL PYTHON

    elif route == "GENERAL":

        answer = general_answer(query)

        return {
            "route": "GENERAL",
            "answer": answer,
            "results": []
        }

    # 4. OUT OF CONTEXT
    else:

        answer = out_of_context_answer()

        return {
            "route": "OUT_OF_CONTEXT",
            "answer": answer,
            "results": []
        }

In [38]:
result = answer_query(
    "what does standard scaler do?"
)

print(result["route"])
print()
print(result["answer"])

Route: RETRIEVE
RETRIEVE

**StandardScaler** removes the mean and scales each feature to unit variance.
It computes the mean and standard deviation on a training set and then transforms data by

\[
X_{\text{scaled}} = \frac{X - \text{mean}}{\text{std}}
\]

so that the transformed features have zero mean and unit variance. This is useful for many estimators that assume centered data with comparable scales.

In [43]:
#import shutil
#
#shutil.make_archive(
#    "/kaggle/working/vector_store",
#    "zip",
#    "/kaggle/working/vector_store"
#)
#
#print("Created:")
#print("/kaggle/working/vector_store.zip")

In [39]:
evaluation_questions = [
    {
        "question": "How do I create a NumPy array?",
        "expected_route": "RETRIEVE"
    },
    {
        "question": "How do I reshape a NumPy array?",
        "expected_route": "RETRIEVE"
    },
    {
        "question": "How do I concatenate arrays in NumPy?",
        "expected_route": "RETRIEVE"
    },
    {
        "question": "How do I create a DataFrame in pandas?",
        "expected_route": "RETRIEVE"
    },
    {
        "question": "What does train_test_split do in scikit-learn?",
        "expected_route": "RETRIEVE"
    },
    {
        "question": "How do I normalize data using scikit-learn?",
        "expected_route": "RETRIEVE"
    },
    {
        "question": "What is a Python list?",
        "expected_route": "GENERAL"
    },
    {
        "question": "What is the capital of France?",
        "expected_route": "OUT_OF_CONTEXT"
    },
    {   "question": "What is a python dictionary?",
        "expected_route": "GENERAL"},
    {   "question": "where is alexandria located?",
        "expected_route": "OUT_OF_CONTEXT"}
]

print(
    f"Number of evaluation questions: "
    f"{len(evaluation_questions)}"
)

Number of evaluation questions: 10

In [40]:
def evaluate_question(question):
    route = route_query(question)
    if route == "OUT_OF_CONTEXT":

        answer = "This question is out of context."

        return {
            "question": question,
            "route": route,
            "retrieved_source": "N/A",
            "retrieved_context": "",
            "answer": answer
        }

    if route == "GENERAL":

        answer = general_answer(question)

        return {
            "question": question,
            "route": route,
            "retrieved_source": "Official Python documentation",
            "retrieved_context": "",
            "answer": answer
        }
    results = faiss_search(
        question,
        top_k=5
    )

    context_parts = []

    for result in results:

        context_parts.append(
            result["text"]
        )

    context = "\n\n".join(
        context_parts
    )

    answer = rag_answer(
        question,
        context
    )
    sources = []

    for result in results:

        metadata = result.get(
            "metadata",
            {}
        )

        sources.append(
            {
                "rank": result.get("rank"),
                "score": result.get("score"),
                "library": metadata.get("library"),
                "source": metadata.get("source"),
                "page": metadata.get("page")
            }
        )


    return {
        "question": question,
        "route": route,
        "retrieved_source": sources,
        "retrieved_context": context,
        "answer": answer
    }

In [41]:
evaluation_results = []

for item in evaluation_questions:

    question = item["question"]

    print("=" * 80)
    print("Question:", question)

    result = evaluate_question(
        question
    )

    evaluation_results.append(
        result
    )

    print("Route:", result["route"])
    print("Answer:", result["answer"])

    print()

================================================================================
Question: How do I create a NumPy array?
Route: RETRIEVE
Answer: You can create a NumPy array in several ways:

| Method | Code example | What it does |
|--------|--------------|--------------|
| **From a Python list or tuple** | `a = np.array([1, 2, 3])`<br>`b = np.array([[1, 2, 3], [4, 5, 6]])` | Builds an array with the same shape as the nested list. |
| **Specify the data type** | `c = np.array([1, 2, 3], dtype=np.float32)` | Creates the array with the given dtype. |
| **Built‑in constructors** | `np.zeros((2, 3))`<br>`np.ones((3, 3))`<br>`np.full((2, 2), 7)`<br>`np.empty((2, 3))`<br>`np.eye(3)`<br>`np.identity(4)`<br>`np.diag([1, 2, 3])` | Generates arrays of zeros, ones, a constant value, uninitialized values, identity matrices, or a diagonal matrix. |
| **Ranges and sequences** | `np.arange(0, 10, 2)`<br>`np.linspace(0, 1, 5)`<br>`np.logspace(0, 3, 4)` | Creates evenly spaced values or log‑spaced values. |
| **Random arrays** | `np.random.rand(2, 3)`<br>`np.random.randn(2, 3)`<br>`np.random.randint(0, 10, 5)` | Generates arrays with random numbers from uniform, normal, or integer distributions. |
| **Array‑like templates** | `np.zeros_like(x)`<br>`np.ones_like(x)`<br>`np.full_like(x, 9)` | Creates an array with the same shape/dtype as `x`, filled with zeros, ones, or a constant. |

These snippets cover the most common ways to create a NumPy array.

================================================================================
Question: How do I reshape a NumPy array?
Route: RETRIEVE
Answer: To change the shape of a NumPy array you use **`reshape`** (or the equivalent `np.reshape` function).

```python
import numpy as np

a = np.arange(12)          # 1‑D array of 12 elements

# 1. Basic reshape – give a new shape as a tuple
b = a.reshape(3, 4)        # 3 rows, 4 columns

# 2. Let NumPy infer one dimension
c = a.reshape(3, -1)       # -1 tells NumPy to compute that size

# 3. Reshape a masked array
#    (same syntax, just with a masked array)
#    >>> np.ma.reshape(a, (2, 6))

# 4. Reshape in place (changes the original array)
#    a.resize((2, 6))      # modifies a directly

# 5. Order of elements can be specified
d = a.reshape(2, 6, order='F')   # Fortran‑style ordering

# 6. View vs copy
#    reshape returns a view when possible; otherwise it makes a copy.
#    For example:
#    >>> a.reshape(3, 4).T   # transpose – still a view
```

**Key points from the documentation**

* `ndarray.reshape(new_shape)` or `np.reshape(a, new_shape)` – returns an array with the same data but a new shape.
* You can pass multiple integers instead of a single tuple: `a.reshape(3, 4)` is the same as `a.reshape((3, 4))`.
* Use `-1` for one dimension to let NumPy infer the size.
* The `order` keyword (`'C'` for C‑style, `'F'` for Fortran‑style) controls how elements are read and written.
* For masked arrays, use `np.ma.reshape` – the syntax is identical.

That’s all you need to reshape a NumPy array.

================================================================================
Question: How do I concatenate arrays in NumPy?
Route: RETRIEVE
Answer: To concatenate arrays in NumPy you use **`np.concatenate`** (or its shorthand `np.concat`).

```python
import numpy as np

# Example
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenate along the default axis (0)
c = np.concatenate([a, b])   # array([1, 2, 3, 4, 5, 6])

# Concatenate along a different axis
# (arrays must have the same shape except in that axis)
# e.g., for 2‑D arrays:
# c = np.concatenate([a2d, b2d], axis=1)
```

**Parameters**

- `arrays`: sequence of array‑like objects to join.
- `axis` (default `0`): the axis along which the arrays will be joined.
- `out`, `dtype`, `casting`: optional arguments for output array, data type, and casting rules.

`np.concatenate` joins the arrays along the specified axis, producing a new array that contains all the input data in order.

================================================================================
Question: How do I create a DataFrame in pandas?
Route: RETRIEVE
Answer: To create a DataFrame in pandas, use the `pd.DataFrame` constructor and pass a dictionary (or list) of column data:

```python
import pandas as pd

# Example using a dictionary
df = pd.DataFrame({
    'col1': [1, 2, 3],
    'col2': ['a', 'b', 'c']
})
```

This will produce a DataFrame with columns `col1` and `col2`. The constructor can also accept lists, NumPy arrays, or other DataFrames.

================================================================================
Question: What does train_test_split do in scikit-learn?
Route: RETRIEVE
Answer: `train_test_split` is a convenience function that splits one or more arrays (or matrices) into random training and test subsets.
It validates the inputs, then uses a `ShuffleSplit` internally to generate indices and returns the split data.

Key points from the documentation:

* Accepts any indexable objects (lists, NumPy arrays, SciPy sparse matrices, pandas DataFrames).
* Parameters `test_size` and `train_size` control the proportion or absolute number of samples in each split.
* `random_state` seeds the random generator for reproducibility.
* `stratify` can be used to perform a stratified split based on a label array.
* Returns a list of length `2 * len(arrays)` containing the train and test splits for each input array.

The function is deprecated in `sklearn.cross_validation` and should be used from `sklearn.model_selection`.

================================================================================
Question: How do I normalize data using scikit-learn?
Route: RETRIEVE
Answer: **Normalizing data in scikit‑learn**

scikit‑learn provides several transformers that scale or normalize your data.
The most common ones are:

| Transformer | What it does | Typical usage |
|-------------|--------------|---------------|
| `StandardScaler` | Subtracts the mean and divides by the standard deviation (z‑score). | `X_scaled = StandardScaler().fit_transform(X)` |
| `RobustScaler` | Uses the median and the inter‑quartile range, robust to outliers. | `X_scaled = RobustScaler().fit_transform(X)` |
| `MinMaxScaler` | Scales each feature to a given range (default 0–1). | `X_scaled = MinMaxScaler().fit_transform(X)` |
| `Normalizer` | Normalizes each sample (row) to a unit norm (`l1`, `l2`, or `max`). | `X_norm = Normalizer(norm='l2').fit_transform(X)` |

### Example

```python
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, Normalizer

# X is your data matrix (n_samples × n_features)

# 1. Standard scaling (z‑score)
X_std = StandardScaler().fit_transform(X)

# 2. Robust scaling (median & IQR)
X_robust = RobustScaler().fit_transform(X)

# 3. Min‑Max scaling to [0, 1]
X_minmax = MinMaxScaler().fit_transform(X)

# 4. Sample‑wise normalization to unit l2‑norm
X_norm = Normalizer(norm='l2').fit_transform(X)
```

- `fit_transform` first learns the scaling parameters from `X` and then applies the transformation.
- `Normalizer`’s `fit` method does nothing; it only rescales each sample.

These transformers can also be used inside pipelines or with sparse matrices (e.g., CSR format for `Normalizer`).

================================================================================
Question: What is a Python list?
Route: GENERAL
Answer: For general Python documentation, visit the official Python documentation:
https://docs.python.org/3/

================================================================================
Question: What is the capital of France?
Route: OUT_OF_CONTEXT
Answer: This question is out of context.

================================================================================
Question: What is a python dictionary?
Route: GENERAL
Answer: For general Python documentation, visit the official Python documentation:
https://docs.python.org/3/

================================================================================
Question: where is alexandria located?
Route: OUT_OF_CONTEXT
Answer: This question is out of context.

In [42]:
import pandas as pd


evaluation_table = []

for result in evaluation_results:

    sources = result["retrieved_source"]

    if isinstance(sources, list):

        source_text = "; ".join(
            [
                (
                    f"{s.get('library')} | "
                    f"{s.get('source')} | "
                    f"Page {s.get('page')}"
                )
                for s in sources
            ]
        )

    else:

        source_text = sources


    evaluation_table.append(
        {
            "Question": result["question"],
            "Route": result["route"],
            "Retrieved Source": source_text,
            "Answer": result["answer"],

            "Context Relevant": "",
            "Grounded": "",
            "Correct": ""
        }
    )


evaluation_df = pd.DataFrame(
    evaluation_table
)


display(
    evaluation_df
)

,Question,Route,Retrieved Source,Answer,Context Relevant,Grounded,Correct
0,How do I create a NumPy array?,RETRIEVE,None | None | Page None; None | None | Page No...,You can create a NumPy array in several ways:\...,,,
1,How do I reshape a NumPy array?,RETRIEVE,None | None | Page None; None | None | Page No...,To change the shape of a NumPy array you use *...,,,
2,How do I concatenate arrays in NumPy?,RETRIEVE,None | None | Page None; None | None | Page No...,To concatenate arrays in NumPy you use **`np.c...,,,
3,How do I create a DataFrame in pandas?,RETRIEVE,None | None | Page None; None | None | Page No...,"To create a DataFrame in pandas, use the `pd.D...",,,
4,What does train_test_split do in scikit-learn?,RETRIEVE,None | None | Page None; None | None | Page No...,`train_test_split` is a convenience function t...,,,
5,How do I normalize data using scikit-learn?,RETRIEVE,None | None | Page None; None | None | Page No...,**Normalizing data in scikit‑learn**\n\nscikit...,,,
6,What is a Python list?,GENERAL,Official Python documentation,"For general Python documentation, visit the of...",,,
7,What is the capital of France?,OUT_OF_CONTEXT,N/A,This question is out of context.,,,
8,What is a python dictionary?,GENERAL,Official Python documentation,"For general Python documentation, visit the of...",,,
9,where is alexandria located?,OUT_OF_CONTEXT,N/A,This question is out of context.,,,

In [43]:
evaluation_judgments = {
    "How do I create a NumPy array?": {
        "Context Relevant": "Yes",
        "Grounded": "Yes",
        "Correct": "Yes"
    },

    "How do I reshape a NumPy array?": {
        "Context Relevant": "Yes",
        "Grounded": "Yes",
        "Correct": "Yes"
    },

    "How do I concatenate arrays in NumPy?": {
        "Context Relevant": "Yes",
        "Grounded": "Yes",
        "Correct": "Yes"
    },

    "How do I create a DataFrame in pandas?": {
        "Context Relevant": "Yes",
        "Grounded": "Yes",
        "Correct": "Yes"
    },

    "What does train_test_split do in scikit-learn?": {
        "Context Relevant": "Yes",
        "Grounded": "Yes",
        "Correct": "Yes"
    },

    "How do I normalize data using scikit-learn?": {
        "Context Relevant": "Yes",
        "Grounded": "Yes",
        "Correct": "Yes"
    },

    "What is a Python list?": {
        "Context Relevant": "N/A",
        "Grounded": "N/A",
        "Correct": "Yes"
    },

    "What is the capital of France?": {
        "Context Relevant": "N/A",
        "Grounded": "N/A",
        "Correct": "Yes"
    },

    "What is a python dictionary?": {
        "Context Relevant": "N/A",
        "Grounded": "N/A",
        "Correct": "Yes"
    },

    "where is alexandria located?": {
        "Context Relevant": "N/A",
        "Grounded": "N/A",
        "Correct": "Yes"
    }
}
for question, judgment in evaluation_judgments.items():

    mask = evaluation_df["Question"] == question

    for column, value in judgment.items():

        evaluation_df.loc[
            mask,
            column
        ] = value

display(evaluation_df)

,Question,Route,Retrieved Source,Answer,Context Relevant,Grounded,Correct
0,How do I create a NumPy array?,RETRIEVE,None | None | Page None; None | None | Page No...,You can create a NumPy array in several ways:\...,Yes,Yes,Yes
1,How do I reshape a NumPy array?,RETRIEVE,None | None | Page None; None | None | Page No...,To change the shape of a NumPy array you use *...,Yes,Yes,Yes
2,How do I concatenate arrays in NumPy?,RETRIEVE,None | None | Page None; None | None | Page No...,To concatenate arrays in NumPy you use **`np.c...,Yes,Yes,Yes
3,How do I create a DataFrame in pandas?,RETRIEVE,None | None | Page None; None | None | Page No...,"To create a DataFrame in pandas, use the `pd.D...",Yes,Yes,Yes
4,What does train_test_split do in scikit-learn?,RETRIEVE,None | None | Page None; None | None | Page No...,`train_test_split` is a convenience function t...,Yes,Yes,Yes
5,How do I normalize data using scikit-learn?,RETRIEVE,None | None | Page None; None | None | Page No...,**Normalizing data in scikit‑learn**\n\nscikit...,Yes,Yes,Yes
6,What is a Python list?,GENERAL,Official Python documentation,"For general Python documentation, visit the of...",N/A,N/A,Yes
7,What is the capital of France?,OUT_OF_CONTEXT,N/A,This question is out of context.,N/A,N/A,Yes
8,What is a python dictionary?,GENERAL,Official Python documentation,"For general Python documentation, visit the of...",N/A,N/A,Yes
9,where is alexandria located?,OUT_OF_CONTEXT,N/A,This question is out of context.,N/A,N/A,Yes

In [44]:
valid_df = evaluation_df[
    evaluation_df["Route"] == "RETRIEVE"
].copy()


def percentage_yes(column):

    values = valid_df[column].astype(str).str.lower()

    if len(values) == 0:
        return 0.0

    return (
        (values == "yes").sum()
        / len(values)
        * 100
    )


retrieval_relevance = percentage_yes(
    "Context Relevant"
)

grounded_percentage = percentage_yes(
    "Grounded"
)

correct_percentage = percentage_yes(
    "Correct"
)


print("=" * 60)
print("EVALUATION RESULTS")
print("=" * 60)

print(
    f"Relevant retrieval: "
    f"{retrieval_relevance:.1f}%"
)

print(
    f"Grounded answers: "
    f"{grounded_percentage:.1f}%"
)

print(
    f"Correct answers: "
    f"{correct_percentage:.1f}%"
)

============================================================
EVALUATION RESULTS
============================================================
Relevant retrieval: 100.0%
Grounded answers: 100.0%
Correct answers: 100.0%

In [45]:
evaluation_path = (
    "/kaggle/working/evaluation_results.csv"
)

evaluation_df.to_csv(
    evaluation_path,
    index=False
)

print(
    "Saved evaluation results to:"
)

print(
    evaluation_path
)

Saved evaluation results to:
/kaggle/working/evaluation_results.csv